### ISSUE TITLE
cannot view pending changes -VS2017

### ISSUE THREAD

**Issue by eltigre4jc** [sboulema/TSVN#31]
Hello I have:
VS2017 Community edition (updated to latest 15.5.2)
TSVN 4.3.23 (latest)
Solution with 2 windows forms projects and 2 DLL projects

It worked for months. But today, I do not know, I already had the TSVN window, wnd when I clicked it gave this:
I disabled/enabled the extension. Uninstalled and installed again. Commit everything I changed in code. Same behavior.
On other project seems to be fine.
Please help, since it's 20000 lines project....

![image](https://user-images.githubusercontent.com/3739046/34721341-09936a74-f54b-11e7-83da-6f6c0c794ce1.png)

Text of exception:
`An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\z003mh7c\AppData\Roaming\Microsoft\VisualStudio\15.0_43133de1\ActivityLog.xml".

Exception details:
System.InvalidCastException: Unable to cast object of type 'SamirBoulema.TSVN.Models.TSVNTreeViewFileItem' to type 'SamirBoulema.TSVN.Models.TSVNTreeViewFolderItem'.
   at SamirBoulema.TSVN.TSVNToolWindowControl.ProcessChange(TSVNTreeViewFolderItem root, String solutionDir, String change)
   at SamirBoulema.TSVN.TSVNToolWindowControl.Update(List`1 pendingChanges, String solutionDir)
   at SamirBoulema.TSVN.TSVNToolWindowControl.HideUnversionedButton_OnChecked(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnChecked(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value)
   at SamirBoulema.TSVN.TSVNToolWindow.OnToolWindowCreated()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()`

**Comment by sboulema** [comment]
Thanks for reporting this bug!

Please try this version and let me know if it solves your problem: https://github.com/sboulema/TSVN/releases/tag/v4.3.25

**Comment by eltigre4jc** [comment]
Just tested!
It works! Thank you!
