### ISSUE TITLE
Crash opening Pending Changes window

### ISSUE THREAD

**Issue by deanis74** [sboulema/TSVN#68]
Version 5.0.707, trying to open the Pending Changes window:

```
System.InvalidOperationException: The tool window 'TSVNToolWindow' has not been initialized.
   at Community.VisualStudio.Toolkit.BaseToolWindow`1.<ShowAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SamirBoulema.TSVN.Commands.TSVNToolWindowCommand.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand`1.<>c__DisplayClass10_0.<<Execute>b__0>d.MoveNext()
```

**Comment by sboulema** [comment]
Should be fixed in the new release 🚀 
Be sure to get the right version because I have splitted the extension in a VS2022 version and a VS2019 and prior version.

Will be on holiday from tomorrow, so new builds will have to wait for a bit 🌞

**Comment by deanis74** [comment]
It's indeed fixed. It doesn't show anything, but I'll dig around to see what I'm missing to get that working.

Enjoy the vacay.

**Comment by sboulema** [comment]
Grab the new release 🚀 (5.1.729)
