### ISSUE TITLE
Version 5.2.1: Crash on opening a solution within an SVN repository

### ISSUE THREAD

**Issue by klylesatepic** [sboulema/TSVN#76]
I get a crash when opening a solution that's within an SVN repository.  Specifically, I get this error message when the TSVN extension loads, and then again when I try to use any of the TSVN functionality:
![image](https://user-images.githubusercontent.com/37372562/137171883-056db7d1-f931-452a-acd2-4a4bd0f769bc.png)

This seems to be new as of version 5.2.1.

Here is the relevant portion of the log file mentioned:
```
  <entry>
    <record>2712</record>
    <time>2021/10/13 16:04:35.948</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [TsvnPackage]</description>
    <guid>{F2E68D5A-C95E-4D53-BBC6-072FF3ED9C53}</guid>
  </entry>
  <entry>
    <record>2713</record>
    <time>2021/10/13 16:04:36.118</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [TsvnPackage]Source: &apos;Microsoft.VisualStudio.Shell.Framework&apos; Description: .ctor must be called on the UI thread.&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8001010E): .ctor must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.ProjectItemsEvents..ctor()&#x000D;&#x000A;   at Community.VisualStudio.Toolkit.Events.get_ProjectItemsEvents()&#x000D;&#x000A;   at SamirBoulema.TSVN.TsvnPackage.&lt;InitializeAsync&gt;d__0.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{F2E68D5A-C95E-4D53-BBC6-072FF3ED9C53}</guid>
    <hr>8001010e</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>2714</record>
    <time>2021/10/13 16:04:36.118</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [TsvnPackage]</description>
    <guid>{F2E68D5A-C95E-4D53-BBC6-072FF3ED9C53}</guid>
    <hr>8001010e</hr>
    <errorinfo></errorinfo>
  </entry>
```

And a cleaned-up version of the error message/stack trace:
SetSite failed for package [TsvnPackage]Source: 'Microsoft.VisualStudio.Shell.Framework' Description: .ctor must be called on the UI thread.
System.Runtime.InteropServices.COMException (0x8001010E): .ctor must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at Community.VisualStudio.Toolkit.ProjectItemsEvents..ctor()
   at Community.VisualStudio.Toolkit.Events.get_ProjectItemsEvents()
   at SamirBoulema.TSVN.TsvnPackage.<InitializeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()

I'm happy to help dig in further if you're unable to reproduce this -- TSVN saves me a lot of time!

**Comment by sboulema** [comment]
Grab the new release! 🚀
